const IcoProfilePublishFields = {
  projectName: 1,
  abbreviation: 1,
  slugUrlToken: 1,
  icoProjectLogo: 1,
  officialWebsiteLink: 1,
  icoWebsiteLink: 1,
  whitePaperLink: 1,
  businessPlanLink: 1,
  projectStatus: 1,
  oneSentenceExplanation: 1,
  mediumLengthDescription: 1,
  icoStartDatetime: 1,
  icoEndDatetime: 1,
  icoEvents: 1,
  fundKeeper: 1,
  coFounders: 1,
  githubLink: 1,
  bitcointalkLink: 1,
  slackLink: 1,
  twitterLink: 1,
  facebookLink: 1,
  redditLink: 1,
  blogLink: 1,
  youtubeLink: 1,
  linkedinLink: 1,
  telegramLink: 1,
  steemitLink: 1,
  weiboLink: 1,
  weChatLink: 1,
  qqLink: 1,
  ratingScore: 1,
  ratingExplanation: 1,
  entityState: 1,
  _id: 1,
  createdAt: 1,
  updatedAt: 1,
};

export default IcoProfilePublishFields;
